### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by refi93** [Web3Auth/single-factor-auth-web#30]
Does this library work with discord custom verfier? Because when I try to pass a discord access token to it, which is shorter/differently formatted than e.g. the google on, I keep getting a `InvalidTokenError: Invalid token specified: missing part #2` error, which points at the `jwtDecode` call failing:

https://github.com/Web3Auth/single-factor-auth-web/blob/43961d1fd44aeba2b0cdb46429d07b5c48924e94/src/Web3Auth.ts#L306

I guess discord's token doesn't really have any part 2 so parsing it to obtain the email/picture/etc seems pointless. Could the `connect()` call perhaps be extended to take `userInfo` from outside which could be used as a fallback if the idToken doesn't contain it? Because the user info is returned from discord, just not encoded within the accessToken, as I understand it

Are you perhaps aware of some other way to make Discord work with this library?

**Comment by refi93** [comment]
@chaitanyapotti I made directly a PR that extends the connect method so that for providers like discord the `userInfo` can be passed from outside: https://github.com/Web3Auth/single-factor-auth-web/pull/31

**Comment by chaitanyapotti** [comment]
Fixed in #31
